brochure/urls.py
from django.urls import path

from . import views

app_name = 'brochure'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('contact/', views.ContactUsView.as_view(), name = 'contact')
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brochure.urls', namespace = 'brochure')),
    path('icecream/', include('icecream.urls', namespace = 'icecream')),
]

icecream/urls.py
from django.urls import path

from . import views

app_name = 'icecream'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
    path('add/', views.CreateView.as_view(), name = 'create'),
    path('all_flavors/', views.AllFlavorView.as_view(), name = 'all_flavors'),
    path('daily_flavors/', views.DailyFlavorView.as_view(), name = 'daily_flavors'),
    path('weekly_flavors/', views.WeeklyFlavorView.as_view(), name = 'weekly_flavors'),
    path('seasonal_flavors/', views.SeasonalFlavorView.as_view(), name = 'seasonal_flavors'),
    path('featured_flavors/', views.FeaturedFlavorView.as_view(), name = 'featured_flavors'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name = 'delete'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name = 'update'),

]

icecream/models.py
from django.db import models
from django.urls import reverse
import datetime

AVAILABLE = [
    ('Daily', 'Daily'),
    ('Weekly', 'Weekly'),
    ('Seasonal', 'Seasonal'),
    ]
BASE = [
    ('Chocolate', 'Chocolate'),
    ('Vanilla', 'Vanilla'),
]
BOOL = [
    (True, 'Yes'),
    (False, 'No')
]

class Icecream(models.Model):
    flavor = models.CharField(max_length = 50)
    base = models.CharField(max_length = 11, choices=BASE)
    available = models.CharField(max_length=9, choices=AVAILABLE)
    Featured = models.BooleanField(choices=BOOL)
    date_churned = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.flavor

    def get_absolute_url(self):
        return reverse('icecream:index')

    class Meta:
        ordering = ['flavor']

brochure/views.py
from django.shortcuts import render
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = 'index.html'

class AboutView(generic.TemplateView):
    template_name = 'about.html'

class ContactUsView(generic.TemplateView):
    template_name = 'contact_us.html'

icecream/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.conf import settings

from .models import Icecream

class IndexView(generic.ListView):
    template_name = 'icecream/index.html'
    model = Icecream

class DetailView(generic.DetailView):
    template_name = 'icecream/detail.html'
    model = Icecream

class CreateView(generic.CreateView):
    template_name = 'icecream/create.html'
    model = Icecream
    fields = '__all__'

class DeleteView(generic.DeleteView):
    template_name = 'icecream/delete.html'
    model = Icecream
    success_url = reverse_lazy('icecream/index.html')
    def get_success_url(self):
        return reverse_lazy('icecream:index')

class UpdateView(generic.UpdateView):
    template_name = 'icecream/update.html'
    model = Icecream
    fields = '__all__'

class AllFlavorView(generic.ListView):
    template_name = 'icecream/all_flavors.html'
    model = Icecream

class DailyFlavorView(generic.ListView):
    template_name = 'icecream/daily_flavors.html'
    model = Icecream
    queryset = Icecream.objects.filter(available='Daily')

class WeeklyFlavorView(generic.ListView):
    template_name = 'icecream/weekly_flavors.html'
    model = Icecream
    queryset = Icecream.objects.filter(available='Weekly')

class SeasonalFlavorView(generic.ListView):
    template_name = 'icecream/seasonal_flavors.html'
    model = Icecream
    queryset = Icecream.objects.filter(available='Seasonal')

class FeaturedFlavorView(generic.ListView):
    template_name = 'icecream/featured_flavors.html'
    model = Icecream
    queryset = Icecream.objects.filter(Featured=True)

brochure/templates/brochure/about.html
{% extends 'brochure/base.html' %}

{% block content %}
<h1>This is the About Page!</h1>
{% endblock content %}

brochure/templates/brochure/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ice Cream Shop</title>
    {% load static %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
    {% include 'brochure/header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'brochure/footer.html' %}
    </div>
</body>
</html>

brochure/templates/brochure/header.html
<div class="row no-gutters" id="header">
    <div class="col-4"><a href="{% url 'brochure:index' %}">Home</a></div>
    <div class="col-4"><a href="{% url 'brochure:about' %}">About</a></div>
    <div class="col-4"><a href="{% url 'icecream:index' %}">Ice Cream</a></div>
</div>

brochure/templates/brochure/index.html
{% extends 'brochure/base.html' %}

{% block content %}
<h1>This is the Home Page!</h1>
{% endblock content %}

icecream/templates/icecream/all_flavors.html
{% extends 'icecream/index.html' %}

{% block content %}
<h2>ALL FLAVORS</h2>
{% for icecream in object_list %}
<p class="flavor-list">
    <a id='flavors' href="{% url 'icecream:detail' icecream.id %}">{{icecream.flavor}}</a>
</p>
{% endfor %}
{% endblock content %}

icecream/templates/icecream/create.html
{% extends 'base.html' %}

{% block content %}

<form style="padding: 30px;" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

icecream/templates/icecream/daily_flavors.html
{% extends 'icecream/index.html' %}

{% block content %}
<h2>DAILY FLAVORS</h2>
{% for icecream in object_list %}
<p class="flavor-list">
<a id='flavors' href="{% url 'icecream:detail' icecream.id %}" >{{icecream.flavor}}</a>
</p>
{% endfor %}
{% endblock content %}

icecream/templates/icecream/delete.html
{% extends 'base.html' %}

{% block content %}
<h2>Delete Flavor</h2>
<form class='delete' method="post">{% csrf_token %}
    <p>Are you sure you want to delete this flavor?</p>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock content %}

icecream/templates/icecream/detail.html
{% extends 'base.html' %}
{% block content %}
<h3>{{ icecream.flavor }}</h3>
<div id='detail-row' class="row no-gutters">
    <div id='detail-item' class="col">Ice Cream Base: <strong>{{ icecream.base }}</strong></div>
</div>
<div id='detail-row' class="row no-gutters">
    <div id='detail-item' class="col">Availability: <strong>{{ icecream.available }}</strong></div>
</div>
<div id='detail-row' class="row no-gutters">
    <div id='detail-item' class="col">Featured Flavor: <strong>{{ icecream.Featured }}</strong></div>
</div>
<div id='detail-row'class="row no-gutters">
    <div id='detail-item' class="col">Churned on: <strong>{{ icecream.date_churned }}</strong></div>
</div>
<div id='detail-row' class="row no-gutters">
    <div id='update-delete' class="col">
<a class='btn btn-primary mr-2' href="{% url 'icecream:delete' icecream.id %}">Delete Flavor</a>
<a class='btn btn-primary ml-2' href="{% url 'icecream:update' icecream.id %}">Update Flavor</a>
</div>
</div>
{% endblock content %}

icecream/templates/icecream/featured_flavors.html
{% extends 'icecream/index.html' %}

{% block content %}
<h2>FEATURED FLAVORS</h2>
{% for icecream in object_list %}
<p class="flavor-list">
<a id='flavors' href="{% url 'icecream:detail' icecream.id %}" >{{icecream.flavor}}</a>
</p>
{% endfor %}
{% endblock content %}

icecream/templates/icecream/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Check out our Ice Cream Lists!</h1>
<div id='test' class="row">
    <a class="col-12" id='nav' href="{% url 'icecream:daily_flavors' %}"><h2>Daily</h2></a>
    <a class="col-12" id='nav' href="{% url 'icecream:weekly_flavors' %}"><h2>Weekly</h2></a>
    <a class="col-12" id='nav' href="{% url 'icecream:seasonal_flavors' %}"><h2>Seasonal</h2></a>
    <a class="col-12" id='nav' href="{% url 'icecream:featured_flavors' %}"><h2>Featured</h2></a>
    <a class="col-12" id='nav' href="{% url 'icecream:all_flavors' %}"><h2>All Flavors</h2></a>
</div>
{% endblock content %}

icecream/templates/icecream/seasonal_flavors.html
{% extends 'icecream/index.html' %}

{% block content %}
<h2>SEASONAL FLAVORS</h2>
{% for icecream in object_list %}
<p class="flavor-list">
<a id='flavors' href="{% url 'icecream:detail' icecream.id %}" >{{icecream.flavor}}</a>
</p>
{% endfor %}
{% endblock content %}

icecream/templates/icecream/update.html
{% extends 'base.html' %}
{% block content %}
<form style="padding: 30px;" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

icecream/templates/icecream/weekly_flavors.html
{% extends 'icecream/index.html' %}

{% block content %}
<h2>WEEKLY FLAVORS</h2>
{% for icecream in object_list %}
<p class="flavor-list">
<a id='flavors' href="{% url 'icecream:detail' icecream.id %}" >{{icecream.flavor}}</a>
</p>
{% endfor %}
{% endblock content %}

templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>What's The Scoop?</h1>
<h4>Our Story...</h4>
<p class="about-us">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id enim cupiditate itaque iusto molestias aspernatur voluptates maiores animi minima odio, quo repudiandae voluptate quod commodi. Explicabo optio at obcaecati modi!
Unde, numquam. Maiores ipsa molestiae vel neque unde laborum eaque, non nulla, natus sed impedit iure velit sunt, architecto numquam culpa quam eius qui quibusdam odio? Commodi esse molestias asperiores.
Hic vero alias necessitatibus magnam nostrum ducimus unde tempora amet repudiandae voluptatibus ipsa molestiae velit quo eligendi est accusantium itaque totam dolorum culpa, corporis neque? Nihil expedita accusantium praesentium nostrum.
Veniam ipsum nisi eveniet possimus nam! Hic quae officia eum, obcaecati suscipit libero odit laboriosam laborum assumenda dolor quam doloremque, voluptatibus quia consectetur repudiandae aperiam magni, nobis deserunt pariatur vel.
Commodi qui temporibus voluptatibus porro molestias placeat reiciendis ipsum? Pariatur totam, recusandae ducimus repudiandae dicta earum facilis nihil neque asperiores aliquam temporibus, eveniet excepturi magni vero, ad quas ipsum accusantium!
Similique ab placeat quidem a voluptatem corrupti sequi excepturi, quis esse. Odit amet quia mollitia ut rem repellendus voluptatum officia nulla veritatis, dolor ducimus quam? Quod totam quibusdam earum facere.
Qui vel voluptatum omnis voluptas, laboriosam officiis libero labore expedita porro consectetur repudiandae accusamus minus veritatis natus molestiae necessitatibus id incidunt alias corrupti, cumque ut, voluptatem quam? Quae, a. Accusamus!
Expedita laborum ea pariatur ad, voluptates iste? Praesentium, ad blanditiis labore ut explicabo cumque officiis veritatis suscipit rerum incidunt error ducimus laborum maiores? Eaque error reprehenderit nihil autem, quasi dolorum!
Architecto, magni natus. Eligendi quasi explicabo esse, earum tenetur cupiditate laudantium sequi illo debitis aperiam saepe necessitatibus dolor voluptatum, rem libero doloribus harum corrupti aliquam fugiat fugit sit deleniti totam.
Corrupti ab culpa dicta. Ratione magni aliquam excepturi! Vel omnis quam debitis amet, possimus laboriosam. Iusto cum accusantium reprehenderit dolore cupiditate fuga, blanditiis sit fugit non unde. Iste, sequi modi.</p>
<br>
<p class="about-us">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque necessitatibus tempore vitae quo, libero voluptatum blanditiis architecto qui nobis voluptatibus tempora amet, impedit eveniet, tenetur porro neque rerum soluta? Veritatis.
Hic assumenda suscipit deleniti cupiditate sint commodi ducimus placeat culpa blanditiis. Quod, odit deserunt quaerat quis ipsa unde earum dolor quo laboriosam soluta odio vel voluptate labore dignissimos esse sint?
In qui iusto reprehenderit voluptatibus aliquid harum odio mollitia ut ratione dignissimos aspernatur non corrupti unde modi illum, eaque quisquam consequuntur doloribus, velit atque, sapiente nulla. Eius et officiis a!
Rem cum provident quasi, obcaecati ad similique fugit ex explicabo totam maiores laudantium ratione hic deleniti aperiam. Dolorem tenetur nobis commodi vero eaque cumque recusandae ducimus ipsa? Ipsam, quis consequuntur!
Saepe officia et voluptatem deserunt tempora maxime quos neque odit architecto praesentium? Ipsum asperiores et natus, nemo expedita nesciunt corrupti quis sint labore quod ab debitis maiores placeat voluptas enim.
Temporibus, atque magni sunt aut aperiam id expedita iure officia! Autem obcaecati doloremque, ut maxime repudiandae nulla cumque fuga odit et quo consequatur dignissimos aliquam officiis labore, veritatis tempore corrupti!
Libero nemo debitis ipsum eum dolore minus possimus veniam eaque labore. Sed temporibus tempora aliquid debitis voluptates nisi perspiciatis amet. Tempora perspiciatis animi libero quasi nam vero quibusdam officia voluptatem.</p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ice Cream Shop</title>
    {% load static %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
    {% include 'header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
</body>
</html>

templates/contact_us.html
{% extends 'base.html' %}

{% block content %}
<h3>By Phone:</h3>
<p style="text-align: center;">
Call 864-867-5309 Monday - Friday, 8:30am - 2:30pm EST. (Ask for Customer Service Desk)
<br>
Greenville, SC Factory Tours Info: 864-501-6210 or toll free (864) SS-CREAM (864-272-7326)
<br>
Ownership Opportunities: 864-555-0123</p>
<h3>By Mail:</h3>
<p style="text-align: center;">Carolina Code School
<br>
411 University Ridge, Suite 235
<br>
Greenville, SC 29601</p>
<h3>Online:</h3>
<p style="text-align: center;">Send a Message!</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="row no-gutters mb-3">
        <input placeholder=' Type message here...' type="text" class='m-auto col-8'></input>
    </div>
    <div class="row no-gutters form-actions">
        <button class='m-auto col-1 btn btn-primary'>Send</button>
    </div>
</form>
{% endblock content %}

templates/footer.html
<div class="row no-gutters" id="footer">
    <div class="col-md"></div>
    <div class="col-md"><a href="{% url 'brochure:index' %}">Home</a></div>
    <div class="col-md"><a href="{% url 'brochure:about' %}">About</a></div>
    <div class="col-md"><a href="{% url 'icecream:index' %}">Flavors</a></div>
    <div class="col-md"><a href="{% url 'brochure:contact' %}">Contact</a></div>
    <div class="col-md"><a href="{% url 'icecream:index' %}">Careers</a></div>
    <div class="col-md"></div>
</div>

templates/header.html
<div class="row no-gutters" id="header">
    <div class="col-1"></div>
    <div class="col"><a href="{% url 'brochure:index' %}">Home</a></div>
    <div class="col"><a href="{% url 'brochure:about' %}">About</a></div>
    <div class="col"><a href="{% url 'icecream:index' %}">Flavors</a></div>
    <div class="col-1"></div>
</div>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Sundae School Ice Cream Parlour</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="https://hips.hearstapps.com/del.h-cdn.co/assets/16/26/1467051342-delish-ice-cream-sandwich-fruity-pebble.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Fruity Pebble Ice Cream Sandwich</h5>
                <!-- <p>For the kid at heart</p> -->
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://www.biggerbolderbaking.com/wp-content/uploads/2019/04/Outrageous-Ice-Cream-Sundaes-Website-Thumbnail1.jpg" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Southern Ice Cream Sundaes</h5>
                <!-- <p>Everyone needs a little Southern Comfort!</p> -->
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://www.loveandoliveoil.com/wp-content/uploads/2019/08/banana-fudge-chunk-ice-cream-FEAT2.jpg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Cookies n Cream</h5>
                <!-- <p>Made fresh everyday!</p> -->
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

{% endblock content %}